### ISSUE TITLE
vascan_search giving 'HTTPResponse' object is not callable

### ISSUE THREAD

**Issue by ghoshbishakh** [sckott/pytaxize#38]
`
>>> import pytaxize
>>> pytaxize.vascan_search(q = ["Helianthus annuus"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/pytaxize-0.4.9900-py3.5.egg/pytaxize/tax.py", line 86, in vascan_search
  File "/usr/lib/python3.5/site-packages/pytaxize-0.4.9900-py3.5.egg/pytaxize/refactor.py", line 44, in raw
TypeError: 'HTTPResponse' object is not callable
`

**Comment by ghoshbishakh** [comment]
however other methods like 
res = pytaxize.Ids('Poa annua', db='col')
res.get_colid()

are working fine

**Comment by ghoshbishakh** [comment]
https://github.com/sckott/pytaxize/blob/b99aa5dc7196919c4404b9873f0bb73ccd4d698b/pytaxize/refactor.py#L44

raw() is not a valid response object method i guess

**Comment by sckott** [comment]
hi @ghoshbishakh thanks for this report. looks like a bug, will fix

**Comment by ghoshbishakh** [comment]
@sckott can I work on it?
I think replacing `.raw` with `.text` can be helpful?

**Comment by sckott** [comment]
yes, go for it!
