### ISSUE TITLE
Make a test suite

### ISSUE THREAD

**Issue by sckott** [sckott/pytaxize#4]
@bendmorris said 

> Since you're already using examples in your docstrings (good practice, very helpful) you might be interested in doctest: http://docs.python.org/2/library/doctest.html

**Comment by sckott** [comment]
someone suggested tox https://testrun.org/tox/latest/

**Comment by sckott** [comment]
@panks @lyttonhao  let's start writing tests for new functions/features/etc.

They go in https://github.com/sckott/pytaxize/tree/master/test - to run tests on the CLI you can run `nosetests` in the root of the repo

**Comment by panks** [comment]
Sure, which all functions we plan to cover?

**Comment by sckott** [comment]
@panks Any new functions/classes you write, or any new features for old functions

**Comment by lyttonhao** [comment]
Okay. @sckott

**Comment by akshayah3** [comment]
I have written tests for the entire `tax` module, will send a PR soon. I am currently working on the `itis` module.

**Comment by sckott** [comment]
will be ongoing, working well now
