### ISSUE TITLE
Add check status code to each function

### ISSUE THREAD

**Issue by sckott** [sckott/pytaxize#6]
With `raise_for_status()`

**Comment by akshayah3** [comment]
Shouldn't [this](https://github.com/sckott/pytaxize/blob/master/pytaxize/tax.py#L353) line be `raise_for_status()`  `instead of raise_for_status`.

I just skimmed through the codebase and I think all the methods which use `requests` have `raise_for_status`.

**Comment by sckott** [comment]
Right, can you go ahead and change those @akshayah3  ?

**Comment by akshayah3** [comment]
@sckott Sure! On it.

**Comment by akshayah3** [comment]
@sckott I think this can be closed now.

**Comment by sckott** [comment]
okay
