### ISSUE TITLE
Name resolution

### ISSUE THREAD

**Issue by sckott** [sckott/pytaxize#8]
cc: @bendmorris @ethanwhite =>

APIs that do name resolution explicitly

- [x] [iPlants TNRS](http://tnrs.iplantcollaborative.org/api.html) - not done
- haven't worked with this one- I assume it's straightforward
- [ ] [Taxosaurus](http://taxosaurus.org/) - not ported yet
- the caveat is that there is no fuzzy matching on names other than plant names.  So ncbi is used for animal names, but no fuzzy 
- [x] [Global names resolver](http://resolver.globalnames.biodinfo.org/api) - already started, if not done

Any others to add?

There are many other APIs that you could use to do name resolution, but are not explicitly done by the API. For example: NCBI, ITIS, theplantlist.org, etc.

**Comment by panks** [comment]
I implement resolver for TNRS. Have a look. Taxosaurus seems to be not working at the moment.

**Comment by sckott** [comment]
re-opening until determine if taxosaurus is totally gone or not
