### ISSUE TITLE
Can't install on Python3

### ISSUE THREAD

**Issue by yoavram** [sckott/pytaxize#9]
I tried to install this on Python 3 - specifically [pyzo2014a](http://www.pyzo.org/downloads.html) - but failed.
It started with syntax errors on 
```
except KeyError, ValueError...
```
which I was able to fix with
```
except (KeyError, ValueError)...
```
then errors on `print` without `()`, but then I got errors in `classification.py` but looking at it, this is R code, not python. So I gave up...

Note that pyzo is a standalone & portable distribution so it can easily be used on a computer that already has python 2 installed.

All errors appeared on the `pip` call.

I wanted to use it for a [class](http://nbviewer.ipython.org/github/yoavram/Py4Life/blob/master/lecture7.ipynb) I'm giving, so if it will be fixed I will be happy to use it, the class is only on May.

**Comment by sckott** [comment]
@yoavram thanks very much for the feedback! 

I am on python `2.7.8` now, so this makes sense.  

Looking around, it seems that many libraries strive to make their library compatible with python 2 (> 2.5 usually) and 3, so I'll try that. Looks like common problems are `print` and error catching http://python3porting.com/noconv.html

Sorry about the R code still in there. I'll try to keep dev stuff on a dev branch from now on, and keep working version in master...

**Comment by sckott** [comment]
@yoavram okay, try installing again...tried to fix all python3 things I could find, and tested on python3 locally and works for me well, but I don't have a test suite yet, so there could be problems still

**Comment by yoavram** [comment]
Great it installs. 
But when I run 
```
D:\>d:\pyzo2014a\python.exe -c "import pytaxize"
```
I get:
```
ImportError: No module named 'simplejson'
```
when I removed `from simplejson import JSONDecodeError` from `gnr.py`, `tax.py` and `gni.py` (apprently it's not used) I get:
```
ImportError: No module named 'lxml'
```
So I think `lxml` needs to be added to requirements, right?
When I add it to `setup.py`, though, I run into this:
```
...
ERROR: b"'xslt-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
** make sure the development packages of libxml2 and libxslt are installed **

Using build configuration of libxslt
d:\pyzo2014a\lib\distutils\dist.py:260: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
error: Setup script exited with error: Unable to find vcvarsall.bat
```

So... I tried using conda (packaged with pyzo, pip might work too) to install lxml.

Then I manage to install `pytaxize` and to import it, with only this warning:
```
d:\pyzo2014a\lib\site-packages\pandas\io\excel.py:626: UserWarning: Installed openpyxl is not supported at this time. Use >=1.6.1 and <2.0.0.
  .format(openpyxl_compat.start_ver, openpyxl_compat.stop_ver))
```
I will open a pull-request.

**Comment by sckott** [comment]
okay, is it working now?  There are still problems I haven't solved with `names_list()` function for importing local datasets, but that shouldn't affect other functions I think

**Comment by yoavram** [comment]
Yeah, works for me!
